// Generated by gencpp from file robot/value_table.msg
// DO NOT EDIT!


#ifndef ROBOT_MESSAGE_VALUE_TABLE_H
#define ROBOT_MESSAGE_VALUE_TABLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot
{
template <class ContainerAllocator>
struct value_table_
{
  typedef value_table_<ContainerAllocator> Type;

  value_table_()
    : table()
    , width(0)
    , height(0)  {
    }
  value_table_(const ContainerAllocator& _alloc)
    : table(_alloc)
    , width(0)
    , height(0)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _table_type;
  _table_type table;

   typedef uint32_t _width_type;
  _width_type width;

   typedef uint32_t _height_type;
  _height_type height;





  typedef boost::shared_ptr< ::robot::value_table_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot::value_table_<ContainerAllocator> const> ConstPtr;

}; // struct value_table_

typedef ::robot::value_table_<std::allocator<void> > value_table;

typedef boost::shared_ptr< ::robot::value_table > value_tablePtr;
typedef boost::shared_ptr< ::robot::value_table const> value_tableConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot::value_table_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot::value_table_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot::value_table_<ContainerAllocator1> & lhs, const ::robot::value_table_<ContainerAllocator2> & rhs)
{
  return lhs.table == rhs.table &&
    lhs.width == rhs.width &&
    lhs.height == rhs.height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot::value_table_<ContainerAllocator1> & lhs, const ::robot::value_table_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot::value_table_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot::value_table_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot::value_table_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot::value_table_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot::value_table_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot::value_table_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot::value_table_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e6c7b62a7859ac6c1c2f046f160fa3f8";
  }

  static const char* value(const ::robot::value_table_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe6c7b62a7859ac6cULL;
  static const uint64_t static_value2 = 0x1c2f046f160fa3f8ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot::value_table_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot/value_table";
  }

  static const char* value(const ::robot::value_table_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot::value_table_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] table\n"
"uint32 width\n"
"uint32 height\n"
;
  }

  static const char* value(const ::robot::value_table_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot::value_table_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.table);
      stream.next(m.width);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct value_table_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot::value_table_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot::value_table_<ContainerAllocator>& v)
  {
    s << indent << "table[]" << std::endl;
    for (size_t i = 0; i < v.table.size(); ++i)
    {
      s << indent << "  table[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.table[i]);
    }
    s << indent << "width: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MESSAGE_VALUE_TABLE_H
